
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA CREATE DATABASE DELETE EQUALS FROM ID INSERT INT INTO KEY LPAREN NUMBER PRIMARY RPAREN SEMICOLON SET STRING TABLE UPDATE USE VALUES VARCHAR WHEREstatement : CREATE DATABASE ID SEMICOLONstatement : USE ID SEMICOLONstatement : CREATE TABLE ID LPAREN column_definitions RPAREN SEMICOLONcolumn_definitions : column_definitions COMMA column_definition\n                          | column_definitioncolumn_definition : ID ID constraintsconstraints : PRIMARY KEY\n                   | emptystatement : INSERT INTO ID LPAREN ID RPAREN VALUES LPAREN value_list RPAREN SEMICOLONvalue_list : value_list COMMA value\n                  | valuevalue : NUMBER\n             | STRINGstatement : UPDATE ID SET ID EQUALS value WHERE ID EQUALS value SEMICOLONstatement : DELETE FROM ID WHERE ID EQUALS value SEMICOLONempty :'
    
_lr_action_items = {'CREATE':([0,],[2,]),'USE':([0,],[3,]),'INSERT':([0,],[4,]),'UPDATE':([0,],[5,]),'DELETE':([0,],[6,]),'$end':([1,15,19,41,49,56,58,],[0,-2,-1,-3,-15,-9,-14,]),'DATABASE':([2,],[7,]),'TABLE':([2,],[8,]),'ID':([3,5,7,8,10,12,17,20,21,23,24,32,44,],[9,11,13,14,16,18,22,24,27,29,30,24,48,]),'INTO':([4,],[10,]),'FROM':([6,],[12,]),'SEMICOLON':([9,13,31,35,36,45,53,55,],[15,19,41,-12,-13,49,56,58,]),'SET':([11,],[17,]),'LPAREN':([14,16,43,],[20,21,47,]),'WHERE':([18,34,35,36,],[23,44,-12,-13,]),'EQUALS':([22,29,48,],[28,37,52,]),'RPAREN':([25,26,27,30,35,36,38,40,42,46,50,51,57,],[31,-5,33,-16,-12,-13,-6,-8,-4,-7,53,-11,-10,]),'COMMA':([25,26,30,35,36,38,40,42,46,50,51,57,],[32,-5,-16,-12,-13,-6,-8,-4,-7,54,-11,-10,]),'NUMBER':([28,37,47,52,54,],[35,35,35,35,35,]),'STRING':([28,37,47,52,54,],[36,36,36,36,36,]),'PRIMARY':([30,],[39,]),'VALUES':([33,],[43,]),'KEY':([39,],[46,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'column_definitions':([20,],[25,]),'column_definition':([20,32,],[26,42,]),'value':([28,37,47,52,54,],[34,45,51,55,57,]),'constraints':([30,],[38,]),'empty':([30,],[40,]),'value_list':([47,],[50,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> CREATE DATABASE ID SEMICOLON','statement',4,'p_statement_create_database','analizador.py',75),
  ('statement -> USE ID SEMICOLON','statement',3,'p_statement_use_database','analizador.py',79),
  ('statement -> CREATE TABLE ID LPAREN column_definitions RPAREN SEMICOLON','statement',7,'p_statement_create_table','analizador.py',83),
  ('column_definitions -> column_definitions COMMA column_definition','column_definitions',3,'p_column_definitions','analizador.py',87),
  ('column_definitions -> column_definition','column_definitions',1,'p_column_definitions','analizador.py',88),
  ('column_definition -> ID ID constraints','column_definition',3,'p_column_definition','analizador.py',95),
  ('constraints -> PRIMARY KEY','constraints',2,'p_constraints','analizador.py',99),
  ('constraints -> empty','constraints',1,'p_constraints','analizador.py',100),
  ('statement -> INSERT INTO ID LPAREN ID RPAREN VALUES LPAREN value_list RPAREN SEMICOLON','statement',11,'p_statement_insert_into','analizador.py',107),
  ('value_list -> value_list COMMA value','value_list',3,'p_value_list','analizador.py',111),
  ('value_list -> value','value_list',1,'p_value_list','analizador.py',112),
  ('value -> NUMBER','value',1,'p_value','analizador.py',119),
  ('value -> STRING','value',1,'p_value','analizador.py',120),
  ('statement -> UPDATE ID SET ID EQUALS value WHERE ID EQUALS value SEMICOLON','statement',11,'p_statement_update','analizador.py',124),
  ('statement -> DELETE FROM ID WHERE ID EQUALS value SEMICOLON','statement',8,'p_statement_delete','analizador.py',128),
  ('empty -> <empty>','empty',0,'p_empty','analizador.py',132),
]
